# Generated by Selenium IDE
import os

import allure
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait


class TestSearch:
    def setup_class(self):
        # jenkins参数化读取浏览器
        browser = os.getenv('browser')
        if browser == 'chrome':
            options = webdriver.ChromeOptions()
        elif browser == 'firefox':
            options = webdriver.FirefoxOptions()
        else:
            options = webdriver.ChromeOptions()

        # 使用remote或者grid模式
        self.driver = webdriver.Remote('http://43.143.71.55:14444', options=options)
        self.driver.implicitly_wait(2)
        self.driver.get("https://ceshiren.com/")
        allure.attach(body=self.driver.get_screenshot_as_png(),attachment_type=allure.attachment_type.PNG)

    def setup(self):
        self.driver.find_element(By.ID, "search-button").click()
        allure.attach(body=self.driver.get_screenshot_as_png(),attachment_type=allure.attachment_type.PNG)

    def teardown(self):
        self.driver.find_element(By.ID, "search-button").click()
        self.driver.find_element(By.CSS_SELECTOR, '.searching .show-advanced-search').click()
        allure.attach(body=self.driver.get_screenshot_as_png(),attachment_type=allure.attachment_type.PNG)

    def teardown_class(self):
        self.driver.quit()

    @pytest.mark.parametrize('keyword', ['selenium', 'requests', 'python'])
    def test_search(self, keyword):
        self.driver.find_element(By.ID, 'search-term').send_keys(keyword)
        self.driver.find_element(By.CSS_SELECTOR, '.searching .show-advanced-search').click()
        WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.CLASS_NAME, 'topic-title'))
        )
        # WebDriverWait(self.driver, 10).until(
        #     expected_conditions.visibility_of_element_located(By.CSS_SELECTOR, '.fps-result-entries>div>div[2]>div>a>span>span>span')
        # )
        assert keyword in self.driver.find_element(By.CLASS_NAME, 'topic-title').text.lower()
